
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Sengaja pakai `process.env.DATABASE_URL` langsung, BUKAN helper `env()`
// dari "prisma/config": `env()` memvalidasi env var itu SEGERA saat config
// ini dimuat, termasuk saat `prisma generate` (yang sebenarnya tidak butuh
// koneksi database sama sekali) — ini bikin `npm install`/postinstall gagal
// di Vercel kalau DATABASE_URL belum terlihat di fase install. Dengan akses
// langsung, nilainya boleh undefined di sini (generate tetap jalan); yang
// benar-benar dipakai untuk connect adalah `url`/`directUrl` di schema.prisma.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL ?? "",
  },
});
